#################################################################################
# A reusable workflow to build all container images for all supported platforms.
#################################################################################

name: Workflow - Build Container Images

on:
  workflow_call:
    inputs:
      build-number:
        description: |
          The build number of the container image.
        type: string
        required: true
      git-ref:
        description: The Git ref used to build the collector.
        type: string
        required: true
      pull-request:
        description: |
          Whether the build is for a pull request.
        type: boolean
        default: false
      version:
        description: |
          The version of the collector binary.
        type: string
        required: true
      workflow-id:
        description: |
          The ID of the GitHub Actions workflow in sumologic-otel-collector to
          fetch artifacts from.
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    # Builds an image for each item in the matrix. Target is the bake target to
    # run. Product is used to group together builds (e.g. ubi) from various bake
    # targets.
    name: >
      ${{ matrix.fips == true && 'Build FIPS' || 'Build' }} -
      ${{
      matrix.os != 'windows' && format('{0}/{1}', matrix.os, matrix.arch)
      ||
      format('{0}/{1}', matrix.target, matrix.arch)
      }}
    uses: ./.github/workflows/workflow-build-container-image.yml
    with:
      arch: ${{ matrix.arch }}
      build-number: ${{ inputs.build-number }}
      fips: ${{ matrix.fips == true }}
      git-ref: ${{ inputs.git-ref }}
      os: ${{ matrix.os }}
      os-version: ${{ matrix.os-version }}
      product: ${{ matrix.product }}
      pull-request: ${{ inputs.pull-request }}
      target: ${{ matrix.target }}
      runs-on: ${{ matrix.runs-on || 'ubuntu-24.04' }}
      version: ${{ inputs.version }}
      workflow-id: ${{ inputs.workflow-id }}
    secrets: inherit
    strategy:
      matrix:
        include:
          # standard product
          - product: standard
            os: linux
            arch: amd64
          - product: standard
            os: linux
            arch: arm64
          - product: standard
            target: windows-ltsc2022
            os: windows
            os-version: 10.0.20348.3807
            arch: amd64
            runs-on: windows-2022
          - product: standard
            target: windows-ltsc2025
            os: windows
            os-version: 10.0.26100.4349
            arch: amd64
            runs-on: windows-2025
          # ubi product
          - product: ubi
            os: linux
            arch: amd64
          - product: ubi
            os: linux
            arch: arm64
          # standard-fips product
          - product: standard-fips
            fips: true
            os: linux
            arch: amd64
          - product: standard-fips
            fips: true
            os: linux
            arch: arm64
          # ubi-fips product
          - product: ubi-fips
            fips: true
            os: linux
            arch: amd64
          - product: ubi-fips
            fips: true
            os: linux
            arch: arm64
